### PR TITLE
Mark up Prettier 2.3.1 changes

### PR DESCRIPTION
**Pull request by 72636c**
This is housekeeping for #445.

### CODE REVIEW

**Review by etaoins — APPROVED** [review]

**Comment by raphsutti** [comment]
Oh sorry, was I meant to do something with changesets? 😅

**Comment by 72636c** [comment]
@raphsutti yeah, though we only have a couple Changesets repos. Hopefully these are easy enough to figure out between the @changeset-bot comment and CONTRIBUTING guides.

**Comment by raphsutti** [comment]
@72636c Are there docs I can look at on how to create changesets for next time?

**Comment by 72636c** [comment]
@raphsutti yes, the @changeset-bot comments on every PR with instructions.

**Pull request merged**
