### PR TITLE
Update templates for Gantry v3

### PR DESCRIPTION
**Pull request by 72636c**

### CODE REVIEW

**Review by AaronMoat — APPROVED** [review]
Do we reliably prompt for a teamName in the owners format?

**Comment by 72636c** [comment]
@AaronMoat great question. We prompt for `Owner` with the initial placeholder `SEEK-Jobs/my-team` as we also use the GitHub org for templating:

> ? For starters, some project details:
> **⊙           Owner : SEEK-Jobs/my-team**
> ⊙            Repo : my-repo
> ⊙        Platform : arm64
> ⊙  Default Branch : main

I think a SEEK-Jobs GitHub team should alway corresponds to an owner, so is this sufficient or is it potentially confusing?

**Comment by AaronMoat** [comment]
Are you saying we're going to pop SEEK-Jobs/my-team into the owner field? Or is teamName just after the /?

**Comment by 72636c** [comment]
@AaronMoat Ah yes, confusing names that don't align with our internal terminology 😅. It gets split:

|||
| :-: | :-: |
| ownerName | SEEK-Jobs/my-team
| orgName | SEEK-Jobs
| teamName | my-team

**Comment by AaronMoat** [comment]
:+1: should be fine for most use cases. We don't have good scanning for "hey you've used an invalid owner" but I imagine we will eventually

**Pull request merged**
