### PR TITLE
Drop region parameterisation

### PR DESCRIPTION
**Pull request by 72636c**
🙊

### CODE REVIEW

**Review by etaoins — COMMENTED** [review]
Is this just for simplification? Would non-Sydney and multi-region services be expected to re-add what they need?

There will be fewer of those than we thought but there are also already Skuba services in SEEK Asia. I want to make sure we’re not being too aggressive here.

**Comment by 72636c** [comment]
@etaoins yep it's purely simplification for newly initialised repos going forwards, and it would need to be re-added for multi-region services.

Granted this is upstreamed from a much-simplified template I'm building for the grad bootcamp, so maybe it's too aggressive.

**Review by etaoins — APPROVED** [review]

**Review by tobyhei — APPROVED** [review]
Is there any newly minted tech guidance written down about the default region we could link to yet?

**Comment by etaoins** [comment]
@tobyhei 

All the recent changes are reflected only in Confluence so far. There’s plans to merge things in to Tech Strategy once we have a better handle on what it should be.

For now `ap-southeast-2` is a safe bet, though.

**Comment by 72636c** [comment]
Also note that the only tangible difference here is that a newly initialised service will not log its `region`. That feels like a reasonable default and saves some $$$ since most of our services are not multi-region.

**Pull request merged**
